{{- if .Values.embeddedCRDs }}
{{- if .Values.rbac.create -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rancher-monitoring-crd.fullname" . }}-crds
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "rancher-monitoring-crd.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-8"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
binaryData:
  crds.gz: {{ .Files.Get "crds.gz.b64" }}
{{- end }}
{{- end }}
