apiVersion: v2
name: gateway-api-crds
description: A Helm chart to install Kubernetes Gateway API CRDs (CustomResourceDefinitions)
type: application
version: 1.2.0
appVersion: "1.2.0"
home: https://gateway-api.sigs.k8s.io/
icon: https://gateway-api.sigs.k8s.io/images/logo/logo-text-horizontal.png
sources:
  - https://github.com/kubernetes-sigs/gateway-api
keywords:
  - gateway
  - gateway-api
  - crd
  - ingress
  - kubernetes
  - networking
maintainers:
  - name: LCW SRE Team
    email: lcwsre@lcwaikiki.com
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/category: networking
